language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5

install:
  - pip install psycopg2
  - pip install django==$DJANGO_VERSION
  - pip install coverage coveralls --use-mirrors


script:
  - coverage run --source=basis setup.py test
  - coverage report

before_script:
  - psql -c 'create database django_basis;' -U postgres

after_success: coveralls
