language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"

env:
  - DJANGO_VERSION=1.5

install:
  - pip install psycopg2
  - pip install django==$DJANGO_VERSION

script: python setup.py test

before_script:
  - psql -c 'create database django_basis;' -U postgres
